name: Registrar
main: com.spinalcraft.registrar.RegistrarPlugin
version: 1.1.0

depend: [UsernameHistory]

commands:
  data:
    description: Retrieve registration data for <player>
    usage: Usage - /data <player>
    permission: registrar.data
    permission-message: No!
  __announce__:
    description: Used by the registration site to announce newly registered players
    usage: Do not use this EVER
    permission: registrar.__announce__
    permission-message: No!
